import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface ContractModel {
  modelVersion: string;
  schemaId: string;
  resourceTypes: string[];
  statuses: string[];
  evidenceTypes: string[];
  benefitTypes: string[];
  deadlineTypes: string[];
  reviewMethods: string[];
  reviewStates: string[];
  schema: Record<string, unknown>;
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const model = JSON.parse(
  await readFile(join(root, "schema/opportunity-v2.model.json"), "utf8"),
) as ContractModel;
const generated = join(root, "generated");
await mkdir(generated, { recursive: true });

const union = (items: string[]) => items.map(JSON.stringify).join(" | ");
const typeSource = `// Generated by scripts/generate-schema-artifacts.ts. Do not edit directly.\n` +
`export const OPPORTUNITY_SCHEMA_VERSION = "2.0" as const;\n` +
`export const RESOURCE_TYPES = ${JSON.stringify(model.resourceTypes)} as const;\n` +
`export const OPPORTUNITY_STATUSES = ${JSON.stringify(model.statuses)} as const;\n` +
`export const EVIDENCE_TYPES = ${JSON.stringify(model.evidenceTypes)} as const;\n` +
`export const BENEFIT_TYPES = ${JSON.stringify(model.benefitTypes)} as const;\n` +
`export type ResourceType = ${union(model.resourceTypes)};\n` +
`export type OpportunityStatus = ${union(model.statuses)};\n` +
`export type EvidenceType = ${union(model.evidenceTypes)};\n` +
`export type BenefitType = ${union(model.benefitTypes)};\n` +
`export interface EvidenceUrl { type: EvidenceType; url: string; checkedAt: string | null; claim: string | null; }\n` +
`export interface OpportunityV2 {\n` +
`  id: string; schemaVersion: "2.0"; provider: string; title: string; aliases: string[]; description: string; canonicalUrl: string | null;\n` +
`  urls: { providerUrl: string | null; programUrl: string | null; applicationUrl: string | null; evidenceUrls: EvidenceUrl[] };\n` +
`  classification: { resourceType: ResourceType; primaryCategory: string; subcategories: string[]; topics: string[]; audiences: string[]; organizationStages: string[]; benefitTypes: BenefitType[]; reviewState: ${union(model.reviewStates)}; defaultSearchEligible: boolean | null };\n` +
`  geography: { global: boolean | null; remote: boolean | null; countries: string[]; excludedCountries: string[]; physicalLocations: string[]; residencyRequired: boolean | null; languages: string[] };\n` +
`  availability: { status: OpportunityStatus; statusReason: string | null; opensAt: string | null; closesAt: string | null; deadlineType: ${union(model.deadlineTypes)}; applicationCycle: string | null; nextExpectedOpening: string | null };\n` +
`  costAndBenefit: { cost: string | null; benefits: Array<{ type: BenefitType; summary: string }>; currency: string | null; amount: number | null; maximumAmount: number | null; benefitSummary: string };\n` +
`  eligibility: { summary: string; studentLevels: string[]; organizationTypes: string[]; companyStages: string[]; ageRestrictions: string | null; incorporationRequired: boolean | null; nonprofitStatusRequired: boolean | null; openSourceRequired: boolean | null; researchAffiliationRequired: boolean | null };\n` +
`  reviewProvenance: { reviewedAt: string | null; reviewMethod: ${union(model.reviewMethods)}; reviewerReference: string | null; claimsChecked: string[]; nextReviewAt: string | null; sourceFetchedAt: string | null; sourceHash: string | null; confidence: number | null; importSource: string | null; extractorVersion: string | null };\n` +
`  changeHistory: { createdAt: string | null; updatedAt: string | null; previousIds: string[]; supersedes: string[]; supersededBy: string[]; tombstone: boolean; removalReason: string | null };\n` +
`  sponsorship: { sponsored: boolean | null; sponsorshipType: string | null; sponsorshipDisclosure: string | null; featuredReason: string | null; featureExpiresAt: string | null };\n` +
`  migration?: { fromSchemaVersion: "1"; legacyStatus: string; legacyRegions: string[]; unresolvedFields: string[] };\n` +
`}\n`;

const formOptions = {
  schemaVersion: "2.0",
  resourceTypes: model.resourceTypes,
  statuses: model.statuses,
  evidenceTypes: model.evidenceTypes,
  benefitTypes: model.benefitTypes,
  deadlineTypes: model.deadlineTypes,
  reviewMethods: model.reviewMethods,
  reviewStates: model.reviewStates,
};
const openApi = {
  components: {
    schemas: {
      OpportunityV2: model.schema,
    },
  },
};
const sql = `-- Generated from schema/opportunity-v2.model.json.\n` +
`-- Apply only in an isolated development database after review.\n` +
`alter table if exists public.opportunities add column if not exists schema_version text;\n` +
`alter table if exists public.opportunities add constraint opportunities_schema_version_v2 check (schema_version in ('1', '2.0')) not valid;\n` +
`alter table if exists public.opportunities add constraint opportunities_v2_status check ((schema_version <> '2.0') or (data->'availability'->>'status' in (${model.statuses.map((item) => `'${item}'`).join(", ")}))) not valid;\n` +
`alter table if exists public.opportunities add constraint opportunities_v2_resource_type check ((schema_version <> '2.0') or (data->'classification'->>'resourceType' in (${model.resourceTypes.map((item) => `'${item}'`).join(", ")}))) not valid;\n`;

const outputs = new Map<string, string>([
  [join(root, "schema/opportunity-v2.schema.json"), `${JSON.stringify(model.schema, null, 2)}\n`],
  [join(generated, "opportunity-v2.ts"), typeSource],
  [join(generated, "form-options.json"), `${JSON.stringify(formOptions, null, 2)}\n`],
  [join(generated, "openapi-components.json"), `${JSON.stringify(openApi, null, 2)}\n`],
  [join(generated, "opportunity-v2.constraints.sql"), sql],
]);

const check = process.argv.includes("--check");
let stale = false;
for (const [path, content] of outputs) {
  if (check) {
    const existing = await readFile(path, "utf8").catch(() => "");
    if (existing !== content) {
      stale = true;
      console.error(`${path.replace(`${root}/`, "")}: generated artifact is stale`);
    }
  } else {
    await writeFile(path, content);
  }
}
if (stale) process.exit(1);
if (!check) console.log(`Generated ${outputs.size} schema v2 artifacts from the canonical model.`);
